# suppress inspection "UnusedProperty" for whole file
writer=console
writer.format={uptime: mm:ss.SSS} {level|min-size=5} {thread|min-size=20} {class-name|min-size=25} {message}
level@org.jetbrains.amper.concurrency=debug
level@org.jetbrains.amper.dependency.resolution=debug
level=info
