# suppress inspection "UnusedProperty" for whole file
writer1=console
writer1.level=info
writer1.format=[test] {uptime: mm:ss.SSS} {level|min-size=5} {thread|min-size=20} {class-name|min-size=25} {message}
writer2=test debug log file
writer2.level=debug
writer2.format={date:yyyy-MM-dd HH:mm:ss.SSS} {level|min-size=5} {thread|min-size=40} {class-name|min-size=25} {message}
level@org.jetbrains.amper.concurrency=debug
level@org.jetbrains.amper.dependency.resolution=debug
level=info
